version: 2
defaults: &defaults
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Check docker is running
          command: docker info
      - run:
          name: Pull Community Hass.io Add-ons build environment
          command: docker pull hassioaddons/build-env:latest
      - checkout
      - deploy:
          name: Build and (maybe) deploy
          command: |
            docker run \
              --privileged \
              -v "$PWD":/docker \
              hassioaddons/build-env:latest \
              --image "hassioaddons/ide-{arch}" \
              --git \
              --target ide \
              --${ARCH}

jobs:
  amd64:
    <<: *defaults
    environment:
      ARCH: amd64
  i386:
    <<: *defaults
    environment:
      ARCH: i386

workflows:
  version: 2
  build_and_maybe_deploy:
    jobs:
      - amd64:
          filters:
            tags:
              only: /.*/
      - i386:
          filters:
            tags:
              only: /.*/
